# Generated by Django 3.1.14 on 2023-03-23 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20230323_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='', max_length=1500, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_eng',
            field=models.CharField(default='', max_length=200, verbose_name='Название английское'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_jpn',
            field=models.CharField(default='', max_length=200, verbose_name='Название японское'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 18, 43, 23, 274734), verbose_name='Время появления'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 18, 43, 23, 274734), verbose_name='Время исчезновения'),
        ),
    ]
