# Generated by Django 3.1.14 on 2023-03-23 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20230323_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='title_eng',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='title_jpn',
            new_name='title_jp',
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 18, 47, 58, 695037), verbose_name='Время появления'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 18, 47, 58, 695037), verbose_name='Время исчезновения'),
        ),
    ]
